### Health check
GET http://localhost:8080/health

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "pass"
}

### Create Account
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "a@a.com",
  "password": "pass"
}

### Purchase asset
POST http://localhost:8080/asset-listings/1/purchase
Content-Type: application/json
Authorization: Bearer MjoxNzY5ODkzMTgxOTQzOjE3Njk4OTY3ODE5NDM6OTg3MjBjZjUtYzdjYy00YzkzLWFjODktMTMzYTYzY2Y3MmU3.a4fvnjDP/4NsWCbi3S8slfTV5l/V/W4SWyrVxYVVSXSaR0YJoRuPxlPm5JjjTxH4KfdpL4Aiqcp/usp9UgUFP/bsS1MFvXUb/feMQvDXzhdSkEIsiI9wZaLtFVK01RA0xwZgZL4BeMazMKJtqtnUef4ueiy4It1EYlKFGwnL3bDPPpXsRvdjIT/i0HGiqoPYep4Ir1UzFcvayX0ORk6MrWqw77yTqgjcspUAo28oUJmOeM2lrQtcvguocSEl3U/qAs3rw4FtiLiWOusxF4GuccEk/V1vV8f4o4+rrVV4amj3tyPOTapuqyjMDAOsPsnbK+kAPrwVmgkeStQ3zlxxxg==

{
  "buyerAccountId": 2
}

### Post assetOffer
POST http://localhost:8080/asset-offers
Content-Type: application/json

{
  "assetUnityId": 1,
  "price": 200.00,
  "token": "MToxNzY5ODkyNjgwOTA1OjE3Njk4OTYyODA5MDU6YzAwNzRhOTgtZDk3MS00OGQwLThlMDUtM2Y5YzgyMTE1Yjdi.jglqagABEbtCTYmHJH3ZYJDW+39uWLswDOyvjp4WY1YZNuBUgkJKI/yWP8hp3gMEghukHTz8pWsZGkMvJQwt6z0RCaVRXKmIIv/ooMkrzQhSVzPJVbHIBzqdi+r1llukS/bz8nLphW7WFv0Q+ERx+//d2e9eCJ7R8jFb9Szcr8dPPRE+KKEsJpNhCzf7HNUxHvU/inVylC+y0/XZAZHAcyDPtkPoXp0cQ910xDp1C3Ua6iq2hcgNvFUub/NAJm5Fp3GpCCZCbg7ntABKxFEFMtkkVuMENNtiKAyToooi5pH7idSkb51+NFj1qspFKjg5IM0F1VLM36oua69IQ1C42g=="
}

### Cancel assetOffer
POST http://localhost:8080/asset-offers/4/cancel
Content-Type: application/json

{
  "accountId": 5,
  "token": "MTA6MTc2OTgyODIyMTM3ODoxNzY5ODMxODIxMzc4OjkyYjA1YTFlLWVlODgtNDQ3NS1hYzg1LWNjOGNmNzBhMDQwNA==.hkQ5c9jaw7BH5/Diunrv3YIDPcGq//tHV6CZ3fd/aaP1Io+GNJHRnA5S0R3WXHowtNLQE6WxcY/dxu5j202zBrnso2sKN8LEAbdQkMoZith0k9l7XXVaaIgflETX+37rqONeQ+d4yINVSeOLJ1h2C7TBIbMeiwUwBMQbyunYjwUo5wYX2yWlXtgnV7d/ccOVOCTwj9S0FDQP7wtRTyEsjQyyEweiLPXsMUR8uzsspiqh8PeLzltAYi5hHyBE4suCrV5LBoAjLufITBxqjoewZBWYIFKo5S11G4ZzP4EWomP3OVjtTt4xUAd2MRgFL13gc3boM8h79e7gXEGqladkIQ=="
}

### Account Deposit
POST http://localhost:8080/accounts/2/deposit
Content-Type: application/json

{
  "amount": 500.00,
  "token": "MjoxNzY5ODkzMDUyNzA1OjE3Njk4OTY2NTI3MDU6M2YzYmY2MWQtYTgyMy00YmQ2LTgwODktNjA4YjBkYTlmYTE5.HXCuQT60TqsOP2dcvwubIC0n2PEcREVw/btD9tv9gQpg5HSydYfSZZ3/L0XiKga11aBxNgDP/5/Q/m48VCHfPuFaZ/a/cwypgY8oZ5xuqIprFtEtPpuJxqjH+IGQbRtD8PTP7BZdjcnD/JYByqxb6g3EnNNyeq5kAyhP6RdZ5Rlo61ZHA7nF96wpreFi+m8yV/uUbGS7gGn2grhQ6VdhjWxvB9YqqVsv/PRHurKQO6uPZlGl14j7nh8JlY2xI3zdOoJ4GNarsBzVT6/H8yB7mK4bt53KULLWxEM9Vv4D/T8GANpEOpWbBfsKN7e9Thg5Md4i44cfsNair1w3w60I7Q=="
}

### Give assetUnity
POST http://localhost:8080/assets/1/units
Content-Type: application/json

{
  "ownerAccountId": 1,
  "token": "MToxNzY5ODkyNjgwOTA1OjE3Njk4OTYyODA5MDU6YzAwNzRhOTgtZDk3MS00OGQwLThlMDUtM2Y5YzgyMTE1Yjdi.jglqagABEbtCTYmHJH3ZYJDW+39uWLswDOyvjp4WY1YZNuBUgkJKI/yWP8hp3gMEghukHTz8pWsZGkMvJQwt6z0RCaVRXKmIIv/ooMkrzQhSVzPJVbHIBzqdi+r1llukS/bz8nLphW7WFv0Q+ERx+//d2e9eCJ7R8jFb9Szcr8dPPRE+KKEsJpNhCzf7HNUxHvU/inVylC+y0/XZAZHAcyDPtkPoXp0cQ910xDp1C3Ua6iq2hcgNvFUub/NAJm5Fp3GpCCZCbg7ntABKxFEFMtkkVuMENNtiKAyToooi5pH7idSkb51+NFj1qspFKjg5IM0F1VLM36oua69IQ1C42g=="
}

### Create Asset bundle
POST http://localhost:8080/assets/bundles
Content-Type: application/json
X-Admin-Token: root

{
  "identifier": "weekly-pack-03",
  "assets": [
    { "text": "X: Rare", "totalSupply": 11 },
    { "text": "E: Epic", "totalSupply": 4 }
  ]
}

### Get Asset bundle
GET http://localhost:8080/assets/bundles

### Get Asset bundle itemns
GET http://localhost:8080/assets/bundles/1/items

### Generate Assets
POST http://localhost:8080/admin/assets/generate
X-Admin-Token: root

### Account Details
GET http://localhost:8080/accounts/5
Authorization: Bearer NzoxNzY5ODMzNzAyNTIwOjE3Njk4MzczMDI1MjA6YTkxNjljYjQtODhjZi00OTE3LWI2YzQtZjk5OWQ4OWUxZGZh.St00T3bYU6l52M2ZwNI4Zqut6Q8SAr6YbHCFAQHI1G7fnErsJwoZ8EKlQgnQsNA0wufZS/5d5OPUBUKRj5/XRuVDspBZQVMIvj432IgiTy/zd6ub63ATdbwm9tv+EVUBpyhv+3mXLLlgN93Uqmt+AZcvU09brZDwHGqG83ajpebSgYYDMSX9O5ZWCNKtj1zmb/e0vScUWTF5iUEMTcFx1KPvg33akInYuxYEFWNiPC830tib5OYgBf0HtjJOT9tJwdX2OXAxQxv5uDAVnCOXLJmFy0CygWZ3v1e2FiJw36Mjo5/8D/5AdSKxWGlwTNxQJS4aDQrE254anvif4IsZOA==

### Client details
GET http://localhost:8080/clients/me
Authorization: Bearer NzoxNzY5ODMzOTUwMTkyOjE3Njk4Mzc1NTAxOTI6ZDg2OGJjNWUtYmJjZC00NTVhLWI1ZmMtMGIwNDhlODA1Zjk0.uDdonalFG3quAc5fejdRV7kX1ZvL296nAkBxjEVQPnZaa9DM+RTFpkBmJrhIhtfGKQowRZ7e4L2ScmjHuD4MfdRoIvrjTFMiRgcpC4JufQtcsciw6bGNhOaCHXC+EBXHu5Nwto3TrwqaXZ1QJ5MJtKnz2hVxitiHX4530g3bX5GT9tQ1bizEn4ZcItQ770A9MHN9qlVcjB2BzIUcNCsyJ6JrJpaMBs6acmRXOdpJbcaA09NFTc1sfsNBR1Wo4XLCgl4sHND4BXSqBiMAD5ymbsVnDsERNxrBvfpEBgoempCiLwSU261DhGNhQ/86RoiZZrO9E42d0nrrP47D8Dxg1g==

### Get transactions by user
GET http://localhost:8080/accounts/5/transfers
Authorization: Bearer NzoxNzY5ODMzMjM1NDEwOjE3Njk4MzY4MzU0MTA6NjIwMGQ1YzItNTQ5Ny00MzdhLTg2NDQtZTdlMzcyY2Q1NGRl.r1Baund2/WSU4D95pt6lC2yV3GVG7qfVqSfWlyzBpygPgdXB1UOwUmkamRIf2HZvwqu00/vJ4bDDgEunh8S6VRqKCcdjpUfOQYZvFpxzXcnzU0ppHUrJyTJSgw1f6nelGdanY3o2VWObBMqZcBj6fP9fPeJ4yq2AXkAd6yPYDTh1IK9Xm5Wz4llEFiyrAziY7BKX0WfZpEHvy3i05PblSJkgbaTX3AJZYDRO/rqggBjilkW7FySpAeZQc8BvrWsXsbVV1fEy8yBODneM48LxpZHWutzyiXiXudAdIDMf7FuMYo7HpyTXKSjfiYqltk7M1j3nh7Kpz5EizxFSG5dj9w==

### GET asset Price History
GET http://localhost:8080/assets/1/price-history

### Get asset price history
GET localhost:8080/asset-listings/5/price-history

### Get asset by id
GET localhost:8080/assets/1

### Get asset listing by id
GET localhost:8080/asset-listings/1

### Get active asset listings active
GET localhost:8080/asset-listings

### Get asset listing by owner
GET localhost:8080/asset-listings?ownerId=5

### Get assets
GET localhost:8080/assets

### Get asset-units by owner
GET localhost:8080//asset-units?ownerId=5
