admin.trigger.token=root
kofi.verification-token=80ccf2e9-7133-4d1e-b24a-af1342f57a4f
google.client-id=1002611612778-n0or7ldrme26ugbgmiccfsc5s1ctif9e.apps.googleusercontent.com
db.default.url=jdbc:postgresql://localhost:5432/postgres
db.default.user=ale
db.default.password=root
db.use.test=false
db.test.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
db.test.user=sa
db.test.password=
webhook.asset.enabled=true
webhook.asset.url=http://localhost:9000/webhook
db.schema.auto-create=true
security.jwt.secret-key=RHVtYnNlY3JldEtleUR1bWJzZWNyZXRLZXkASDADASD=
security.jwt.expiration-time=86400000
