admin.trigger.token=root
db.default.url=jdbc:postgresql://localhost:5432/postgres
db.default.user=ale
db.default.password=root
db.use.test=false
db.test.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
db.test.user=sa
db.test.password=
